### ISSUE TITLE
Add a `test_synthetic_data.py` module using scope-generated TPFs

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#531]
This issue describes a project which I would like @gully to work on when he returns from leave (and I may be gone).

In brief, I would like us to use @nksaunders' excellent [scope package](https://github.com/nksaunders/scope) to generate three synthetic TPF files, and then use those synthetic files to add a new unit test module. Specifically, I propose the following two-phase plan:

## Phase 1: Generate three synthetic TPF files

The first step is to use `scope` to generate three synthetic TPFs with the following requirements:

- The three TPFs shall each contain a single star with K2-like noise and motion.
- The three TPFs shall use different input light curves:
  * `synthetic-k2-flat.targ.fits` shall use a flat light curve;
  * `synthetic-k2-sinusoid.targ.fits` shall use a low-frequency sinusoid (e.g. 5-day period);
  * `synthetic-k2-planet.targ.fits` shall use a short-period Neptune-sized planet (e.g. Kp = 14; planet period = 5 days; transit depth = 2000ppm).
- The TPFs shall include the input star position and light curves in the FITS file, e.g. as part of an extra "ground truth" extension, so that we can easily verify signal recovery.  Scope may already do this out of the box. If not, I recommend preparing a scope PR to add this feature.
- The TPFs shall be sufficiently small to be added to the git repository, i.e. a few hundred Kb max.
- The TPFs shall be added to the Lightkurve repository under `lightkurve/tests/data/synthetic` alongside a README file which documents how the files were generated.

## Phase 2: Add unit test module

Once the three synthetic files are generated, the second step will be to create a new test module called `lightkurve/tests/test_synthetic_data.py` which performs the following sanity checks:

1. Can each of the three input light curves be recovered to a good level of accuracy after applying `SFFCorrector`?
2. Same for `PLDCorrector`?
3. Can the sinusoid period successfully be recovered from `synthetic-k2-sinusoid.targ.fits` using our `LombScarglePeriodogram` class?
4. Can the Neptune-sized planet period and depth be recovered from `synthetic-k2-planet.targ.fits` using our `BoxLeastSquaresPeriodogram` class?
5. Can the star positions be recovered to a good level of accuracy using `tpf.estimate_centroids()`?

There are a lot more tests and data challenges we can imagine executing using `scope`, but let's start with the simple TPFs and tests described above!

**Comment by gully** [comment]
Progress so far: 


- [x] The three TPFs shall each contain a single star with K2-like noise and motion.
- The three TPFs shall use different input light curves:
     - [x] `synthetic-k2-flat.targ.fits` shall use a flat light curve;
     - [x] `synthetic-k2-sinusoid.targ.fits` shall use a low-frequency sinusoid (e.g. 5-day period);
     - [x] `synthetic-k2-planet.targ.fits` shall use a short-period Neptune-sized planet (e.g. Kp = 14; planet period = 5 days; transit depth = 2000ppm).

- [x] The TPFs shall include the input star position and light curves in the FITS file, e.g. as part of an extra "ground truth" extension, so that we can easily verify signal recovery. Scope may already do this out of the box. If not, I recommend preparing a scope PR to add this feature.
- [x] The TPFs shall be sufficiently small to be added to the git repository, i.e. a few hundred Kb max.
- [x] The TPFs shall be added to the Lightkurve repository under `lightkurve/tests/data/synthetic` alongside a README file which documents how the files were generated.

**Comment by gully** [comment]
Ok, I completed Phase 2 in the ongoing pull request.

**Comment by gully** [comment]
Closed by the above PR
